dist: xenial
os: linux
language: ruby
rvm:
 - 2.3.3
cache: bundler
sudo: true
service:
    -docker
before_install:
  - sudo apt-get update  
  - sudo apt install nodejs-legacy  
  - npm -v
  - node -v
  - sudo npm install -g sql-cli
  - sudo apt-get install unixodbc-dev  

  - sudo docker pull microsoft/mssql-server-linux  
  - docker run --name dbserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Rsp3cRsp3c' -p 1433:1433 -d microsoft/mssql-server-linux
  - docker ps -a
  - docker start dbserver
  
  