language: ruby
rvm:
 - 2.3.3
cache: bundler
sudo: true
service:
    -docker
before_install:
  - sudo apt-get install unixodbc-dev
  - sudo docker pull microsoft/mssql-server-linux
dist: xenial
os: linux