dist: xenial
os: linux
language: ruby
rvm:
 - 2.3.3
cache: bundler
sudo: true
service:
    -docker
before_install:
  - sudo apt-get update
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
  - sudo apt-get install -y mssql-tools unixodbc-dev

  - sudo docker pull microsoft/mssql-server-linux  
  - docker run --name dbserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Rsp3cRsp3c' -p 1433:1433 -d microsoft/mssql-server-linux
  - docker ps -a
  - docker start dbserver
  
  - sudo apt install npm
  - sudo apt install nodejs-legacy
  - sudo npm install -g sql-cli