# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e085d535667b41ba3f11afffdb777b2d62833dc22f1821fd661ff4634652123900208ab50cc2db7aa882f272b9e2428aac9f6dc63164e6b4fa5f17cabfaa7e21

test:
  secret_key_base: 76fc59dafd4e5d9ce432105f92e8e82e3c9f477b9df8111f3b1d89ce64d170ab64c7a878e8e6f9ea09bc443b4e023041a15ac5242423db04192ff4fef192a835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
